src/controllers/template_controller.py
from flask import Blueprint, render_template
from utils.data_loader import DataLoader

template_blueprint = Blueprint('template', __name__)

data_loader = DataLoader('data/Travel.csv')
data = data_loader.pre_process_travel_data(data_loader.data)

@template_blueprint.route('/')
def index():
    return render_template('index.html')

@template_blueprint.route('/demo')
def ga_demo():
    return render_template('demo/ga_demo.html')

@template_blueprint.route('/pricing/company')
def pricing_for_company():
    return render_template('pricing/company_pricing.html')

@template_blueprint.route('/pricing/customer')
def pricing_for_customer():
    return render_template('pricing/customer_pricing.html')

@template_blueprint.route('/pricing/cost')
def pricing_cost():
    return render_template('pricing/cost_calculation.html')

src/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename= 'css/pico.min.css') }}">
    <title>{% block title %}{% endblock %}</title>
</head>

<body class="wrapper">
        <header class="page-header">
            <nav>
                <ul>
                    <li><strong><a href="{{ url_for('template.index') }}">WS2023 CMKE G9</a></strong></li>
                </ul>
            </nav>
        </header>
        <main class="page-body container">
            <div>
                {% block header %}{% endblock %}
            </div>
            {% block content %}{% endblock %}
        </main>
        <footer class="page-footer">
            <div class="grid">
                <p>© 2024 WS2023 CMKE G9</p>
            </div>
        </footer>
    {% block script %}{% endblock %}
</body>

</html>

src/templates/index.html
{% extends 'base.html' %}
{% block title %}Landing Page{% endblock %}
{% block header %}<h1>Topic 9: Optimize price to handle request</h1>{% endblock %}
{% block content %}
        <p>Choose an option to get started.</p>
        <ul>
            <li><a href="{{ url_for('template.ga_demo') }}">Demo</a></li>
            <li><a href="{{ url_for('template.pricing_for_company') }}">Company Pricing</a></li>
            <li><a href="{{ url_for('template.pricing_for_customer') }}">Customer Pricing</a></li>
            <li><a href="{{ url_for('template.pricing_cost') }}">Cost Calculation</a></li>
        </ul>
{% endblock %}
</body>
</html>

src/templates/swagger_ui.html
<!DOCTYPE html>
<!-- https://github.com/sunnyagarwal008/setup-swagger-ui-in-one-page/blob/master/swagger-ui.html
 //-->
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Swagger Optimize Pricing</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@3//swagger-ui.css" >
    <style>
      html
      {
        box-sizing: border-box;
        overflow: -moz-scrollbars-vertical;
        overflow-y: scroll;
      }

      *,
      *:before,
      *:after
      {
        box-sizing: inherit;
      }

      body
      {
        margin:0;
        background: #fafafa;
      }
    </style>
  </head>

  <body>
    <div id="swagger-ui"></div>

    <script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@3/swagger-ui-standalone-preset.js"></script>
    <script>
      window.onload = function() {
      const ui = SwaggerUIBundle({
        url: "{{ url_for('get_spec') }}",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "BaseLayout"
      })
    }
    </script>
  </body>
</html>